version: '2'

services:
 bgp:
    build: ./docker/bgp/.
    volumes:
      - ./docker/bgp/r1/zebra.conf:/etc/quagga/zebra.conf:ro
      - ./docker/bgp/r1/ospfd.conf:/etc/quagga/ospfd.conf:ro
      - ./docker/bgp/r1/bgpd.conf:/etc/quagga/bgpd.conf:ro
      - ./docker/bgp/supervisord.conf:/etc/supervisord.conf:ro
    image: bgp:AS6600
    privileged: true
    ports:
      #admin
      - 10201:2601
      #ospf
      - 10204:2604
      #bgp
      - 10205:2605
    networks:
      afuera:
        ipv4_address: 70.0.0.6
      nr1:
        ipv4_address: 200.9.20.2
      nr2:
        ipv4_address: 200.9.21.2
      nr3: 
        ipv4_address: 200.9.21.34

 bind9:
    build: ./docker/dns/bind9/.
    image: sameersbn/bind:latest
    privileged: true
    restart: always
    dns: 127.0.0.1
    environment:
      - ROOT_PASSWORD=SecretPassword
    ports:
     - 10000:10000
     #- "53:53/udp"
     #- "53:53/tcp"
    volumes:
     - ./docker/dns/volumes/webmin:/data
    networks:
     nr3:
      ipv4_address: 200.9.21.35

 host1:
    image: alpine
    privileged: true
    command: top
    networks:
      nr1:
        ipv4_address: 200.9.20.10


networks:
  afuera:
    driver: "bridge"
    ipam:
      driver: default
      config:
        - subnet: 70.0.0.0/24

  nr1:
    driver: "bridge"
    ipam:
      driver: default
      config:
        - subnet: 200.9.20.0/24

  nr2:
    driver: "bridge"
    ipam:
      driver: default
      config:
        - subnet: 200.9.21.0/27

  nr3:
    driver: "bridge"
    ipam:
      driver: default
      config:
        - subnet: 200.9.21.32/29

